### DISCUSSION TITLE
response serialisation for response maps

### DISCUSSION THREAD

**Discussion by commonism** [fastapi/fastapi#10039] [Questions] [answered]
### First Check

- [X] I added a very descriptive title here.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/pydantic/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import io

from fastapi import FastAPI, Response, Body
from pydantic import BaseModel

import yaml

app = FastAPI()

class schema:
    class Pet(BaseModel):
        name: str
        weight: int|None
        color: str|None = None

    class Error(BaseModel):
        code: int
        message: str

@app.post(
    "/pet",
    operation_id="createPet",
    response_model=schema.Pet,
    responses={201: {"model": schema.Pet}, 409: {"model": schema.Error}},
)
def createPet(
    response: Response,
    pet: schema.Pet = Body(..., embed=True),
) -> schema.Pet:
    response.status_code = 201
    return pet

from fastapi.testclient import TestClient
client = TestClient(app)


def test_pet():
    response = client.get("""/openapi.json""")
    data = response.json()
    f = io.StringIO()
    yaml.safe_dump(data, f)
    f.seek(0)
    print(f.read())

    assert (a:=(r:=data["paths"]["/pet"]["post"]["responses"])["200"]["content"]["application/json"]["schema"]["$ref"]) == (b:=r["201"]["content"]["application/json"]["schema"]["$ref"]), f"{a} != {b}"

test_pet()
```

### Description

Introduced in https://github.com/tiangolo/fastapi/commit/19a2c3bb54ecef5fab936b45e4c262b283e100f6
I'd expect all outputs to be of the output data type.

The pydantic version of the model representation is different, fastapi skips the default value and splits the model default-value into  in/out.
pydantic Pet
```yaml
properties:
  color:
    anyOf:
    - type: string
    - type: 'null'
    default: null
    title: Color
  name:
    title: Name
    type: string
  weight:
    anyOf:
    - type: integer
    - type: 'null'
    title: Weight
required:
- name
- weight
title: Pet
type: object
```

color lacks a default value - but not required
```yaml
    Pet-Input:
      properties:
        color:
          anyOf:
          - type: string
          - type: 'null'
          title: Color
        name:
          title: Name
          type: string
        weight:
          anyOf:
          - type: integer
          - type: 'null'
          title: Weight
      required:
      - name
      - weight
      title: Pet
      type: object
```

color lacks a default value and is required - how does this correlate to the pydantic model definition?
```yaml
    Pet-Output:
      properties:
        color:
          anyOf:
          - type: string
          - type: 'null'
          title: Color
        name:
          title: Name
          type: string
        weight:
          anyOf:
          - type: integer
          - type: 'null'
          title: Weight
      required:
      - name
      - weight
      - color
      title: Pet
      type: object
```      

Is there any documentation of the purpose and usefulness of the split in models for in/out?
I'm sure clients won't enjoy having 2 models which do not interchange instead of one.

### Operating System

Linux

### FastAPI Version

0.101.0

### Pydantic Version

2.1.1

### Python Version

3.10.12
