### DISCUSSION TITLE
Fast Api mock not working in pipeline attemps to connect to the db

### DISCUSSION THREAD

**Discussion by krivas** [fastapi/fastapi#10660] [Questions]
### First Check

- [X] I added a very descriptive title here.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/pydantic/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from unittest.mock import MagicMock
import pytest 
from main import app
from routers.contacts import get_db


mock_session=MagicMock()

def override_get_db():
    try:
        yield mock_session
    finally:
        pass

app.dependency_overrides[get_db] =  override_get_db

@pytest.fixture
def mock_db_session():
    return mock_session
```

### Description

I'm getting the error: "Can't connect to MySQL server on 'localhost' in the pipeline but it shouldn't because I'm mocking the connection with magic mock. The tests work perfectly in my local machine but not in the pipeline.

The error: ImportError while loading conftest '/home/runner/work/gitworkflow2/gitworkflow2/backend/tests/conftest.py'. tests/conftest.py:3: in from main import app main.py:11: in Base.metadata.create_all(bind=engine)

E sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 111] Connection refused)")

My code
```
from unittest.mock import MagicMock, patch
from data.models import Contact
from fastapi.testclient import TestClient
from routers.contacts import get_db
from main import app


client = TestClient(app)


def test_create_contact(mock_db_session):
    url="/contacts"
    contact={"first_name":"Giovanni",
             "last_name":"Rossi",
             "email":"giovanni@gmail.com",
             "phone_number":"1234567890" ,
             "user_id":1
             }

    response = client.post(url, json=contact)

    assert response.status_code == 201
    data = response.json()
    assert data["first_name"] == "Giovanni"
    assert data["last_name"] == "Rossi"
    assert data["phone_number"] == "1234567890"
    assert data["email"] == "giovanni@gmail.com"


    mock_db_session.add.assert_called_once()
    mock_db_session.commit.assert_called_once()
    mock_db_session.refresh.assert_called_once()

def test_create_without_user_id(mock_db_session):
    url="/contacts"
    contact={"first_name":"Giovanni",
             "last_name":"Rossi",
             "email":"giovanni@gmail.com",
             "phone_number":"1234567890" ,
             }

    response = client.post(url, json=contact)
    assert response.status_code == 422

def test_create_without_phone_number(mock_db_session):
    url="/contacts"
    contact={"first_name":"Giovanni",
             "last_name":"Rossi",
             "email":"giovanni@gmail.com",
             "user_id":1
             }

    response = client.post(url, json=contact)
    assert response.status_code == 422

def test_get_contacts(mock_db_session):

    mock_query = MagicMock()
    mock_query.filter.return_value.all.return_value = [
    {
        "last_name": "Rossi",
        "id": 68,
        "phone_number": "1234567890",
        "email": "giovanni@gmail.com",
        "user_id": 1,
        "first_name": "Giovanni"
    }
    ]

    mock_db_session.query.return_value = mock_query

    app.dependency_overrides[get_db] = lambda:mock_db_session
    response = client.get("/contacts/1")
    assert response.status_code == 200
    assert response.json() == [
    {
        "last_name": "Rossi",
        "id": 68,
        "phone_number": "1234567890",
        "email": "giovanni@gmail.com",
        "user_id": 1,
        "first_name": "Giovanni"
    }
    ]

def test_get_empty_contacts(mock_db_session):

    mock_query = MagicMock()
    mock_query.filter.return_value.all.return_value = []

    mock_db_session.query.return_value = mock_query

    app.dependency_overrides[get_db] = lambda:mock_db_session
    response = client.get("/contacts/1")
    assert response.status_code == 200
    assert response.json() == []



```
Main:
```

from fastapi import Depends, FastAPI
from fastapi.middleware.cors import CORSMiddleware
from typing import Annotated
from data.database import engine,SessionLocal
from data.models import Base
from sqlalchemy.orm import Session 
from routers import contacts, users

app = FastAPI()
Base.metadata.create_all(bind=engine)

def get_db():
    db=SessionLocal()
    try:
        yield db
    finally:
        db.close()

db_dependency=Annotated[Session,Depends(get_db)]
# Configure CORS to allow requests from your Angular frontend


origins = ["*"]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
app.include_router(contacts.router, prefix="/contacts", tags=["Contacts"])
app.include_router(users.router, prefix="/users", tags=["Users"])

@app.get("/health" ,tags=['Health'])
async def check_health():
    return {"Hello": "World"}
```

My pipeline
```
name: CI

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10.9]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  

    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        

        
    - name: Install Dependencies
      working-directory: ./backend
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: ./backend
      run: |
       source venv/bin/activate
       pip install mock
       python -m pytest tests/test_users.py
```

### Operating System

macOS

### FastAPI Version

0.104.1

### Pydantic Version

2.4.2

### Python Version

3.10.9
