### DISCUSSION TITLE
Logically “or”ed scopes

### DISCUSSION THREAD

**Discussion by jeffsawatzky** [fastapi/fastapi#11477] [Questions]
If I have an endpoint that requires the OAuth token to have either the "admin" scope OR "item:write" scope OR "all:write" scope, how would I express this with the `Security` and `SecurityScopes` dependencies?

The OAS spec seems to allow this
https://swagger.io/docs/specification/authentication/#multiple

And it would look something like this
```
security:
  - oauth2: [admin]
  - oauth2: [item:write]
  - oauth2: [all:write]
```

https://github.com/OAI/OpenAPI-Specification/discussions/3001#discussioncomment-3456275

Thanks!
