### DISCUSSION TITLE
Uvicorn reload on container startup

### DISCUSSION THREAD

**Discussion by MaelAbgrall** [fastapi/fastapi#3209] [Questions] [answered]
Hello everyone!

I recently started to use fastAPI, however I an odd issue with uvicorn.

I built an app using a custom docker with live reload (see below), I found that changing the source code when the container is off will trigger a lot of StatReload (one for every file modified). The worst case scenario is my friend working on the frontend, who get a huge amount of reload every time he pulls the updated source.

Nothing very important, but I' just curious is there is a way to have only one reload instead?

the compose
```yml
  core:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    ports: 
      - 8000:8000
    volumes: 
      - ./:/core #for live reload
    env_file: 
      - ./.env
    depends_on: 
      - db
```
and the build
```Dockerfile
FROM python:3.8

EXPOSE 8000

# set work directory
WORKDIR /core

# set environment variables
# this prevents to write .pyc files to disk
ENV PYTHONDONTWRITEBYTECODE 1
# this prevents python to buffer stdout and stderr
ENV PYTHONUNBUFFERED 1

# # install system dependencies
# RUN apt-get update \
#   && apt-get -y install netcat gcc postgresql \
#   && apt-get clean

# install python dependencies
RUN pip install --upgrade pip
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . ./
```
