### DISCUSSION TITLE
Mypy fails when I use explicit Path, Query or Body for params

### DISCUSSION THREAD

**Discussion by SergeyTsaplin** [fastapi/fastapi#5127] [Questions] [answered]
Hello, I have the following code:

```python
from fastapi.params import Body
...

@router.patch("projects/{project_name}/clusters/{cluster_name}")
async def patch_project_cluster(
    project_name: str,
    cluster_name: str,
    patch: JsonPatch = Body(),
) -> Cluster:
    ...

```

when I run mypy over it, it fails:

```
Incompatible default for argument "patch" (default has type "Body", argument has type "JsonPatch")
```

How can I deal with it without `# type: ignore`?

```toml
...
[tool.poetry.dependencies]
pydantic = "^1.9.1"
fastapi = "^0.78.0"
...

[tool.poetry.dev-dependencies]
mypy = "^0.961"
...
[tool.mypy]
strict = true
plugins = "pydantic.mypy"
```
