### DISCUSSION TITLE
k8s Ingress and FastAPI Routing

### DISCUSSION THREAD

**Discussion by krisdeveloper25** [fastapi/fastapi#5231] [Questions]
I am running into a issue with configuration running on kubernetes/minikube and local non-kubernetes/minikube setup.  Here is the issues I am running into with the URLs:

- minikube (run locally on dev machine)
-- [SUCCESS] http://localhost/API/
-- [SUCCESS] http://localhost/API/docs
-- [SUCCESS] http://localhost/API/redoc
- non-minikube (run locally on dev machine)
-- [SUCCESS] http://127.0.0.1:8000/
-- [FAILED] http://127.0.0.1:8000/API/
--- Getting "This site can’t be reached"
-- [FAILED] http://127.0.0.1:8000/API/docs
--- Getting "This site can’t be reached"
-- [FAILED] http://127.0.0.1:8000/API/redoc
--- Getting "This site can’t be reached"
-- [FAILED] http://127.0.0.1:8000/docs
--- Getting error: "Failed to load API definition.  Fetch error.  Not Found /API/openapi.json"
-- [FAILED] http://localhost/API/
--- Getting "This site can’t be reached"
-- [FAILED] http://localhost/API/docs
--- Getting "This site can’t be reached"
-- [FAILED] http://localhost/API/redoc
--- Getting "This site can’t be reached"

The Python source code has the following root path:
`
app = FastAPI(root_path="/API")
`

The kubernetes ingress is configured the following way:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: local-ingress
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 3m
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /API/(.*)
        pathType: Prefix
        backend:
          service:
            name: myapp
            port:
              number: 8000
```

Here is the questions I have:
- Do I need two separate configurations: (1) non-kubernetes source code, (2) kubernetes specific setup?

I'd like to be able to access the APIs and documentation no matter which development setup I am using.  I'd also would like to be able to access them using the same URLs.
