### DISCUSSION TITLE
links created by url_for in Jinja2 template use HTTP instead of HTTPS

### DISCUSSION THREAD

**Discussion by Lepiloff** [fastapi/fastapi#6073] [Questions]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
main.py

from fastapi import FastAPI, Request, Form
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

from db import database
from helpers.middleware import get_user_notifications, set_custom_attr
from models.users import users
from routes import api_router
from sessions.core.base import redis_cache

app = FastAPI()

app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")

views.py

@router.get('/', response_class=HTMLResponse)
async def main_page(request: Request,
                    user: User = Depends(UserService.get_authenticated_user_id)
                    ):
    return templates.TemplateResponse('base.html',
                                      context={
                                          'request': request,
                                          'user': user,
                                      }
                                      )

html

  <link type="text/css" href="{{ url_for('static', path='/css/materialize.min.css') }}" rel="stylesheet">
  <link type="text/css" href="{{ url_for('static', path='/css/custom.css') }}" rel="stylesheet">
```

### Description

I run the application in the docker via Uvicorn and use nginx as a proxy server. Everything was working until I configured ssl and started using https protocol. Now when I click on the [team-mate.app](link) get

`Mixed Content: The page at 'https://team-mate.app/' was loaded over HTTPS, but requested an insecure stylesheet 'http://team-mate.app/static/css/materialize.min.css'. This request has been blocked; the content must be served over HTTPS.`

I tried the advice I found and ran Uvicorn through --proxy-headers

Dockerfile
....
`CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers"]`

docker-compose.yaml
```
....
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload --proxy-headers"
```

But nothing has changed. The problem remains. 
Maybe I misunderstood the advice or the nginx config needs to be edited somehow. 

The second way I used

```
from fastapi.middleware.httpsredirect import HTTPSRedirectMiddleware
app = FastAPI()
app.add_middleware(HTTPSRedirectMiddleware)
```

But got  `HTTP/1.0" 307 Temporary Redirect ` for all my urls

### Operating System

Linux

### FastAPI Version

fastapi==0.89.1

### Python Version

3.10.6

### Additional Context

I run the application in the docker via Uvicorn and use nginx as a proxy server. Everything was working until I configured ssl and started using https protocol.

**nginx config**

```
server {
    listen 80;
    server_name team-mate.app;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 443 ssl;
    server_name team-mate.app;
    server_tokens off;

    location /static/ {
        gzip            on;
        gzip_buffers    8 256k;
        root /app;
    }

    ssl_certificate /etc/letsencrypt/live/team-mate.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/team-mate.app/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header    Host                $http_host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
    }
}
```

Dockerfile

```
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
```

**docker-compose.yaml**
```

version: '3.9'

services:
  web:
    env_file: .env
    build: .
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      .....
      .....
```

**Comment by jgould22** [comment]
This may help you https://stackoverflow.com/questions/70521784/fastapi-links-created-by-url-for-in-jinja2-template-use-http-instead-of-https

**Comment by Lepiloff** [comment]
@jgould22  tried this way. Сonceptually nothing has changed, although there is a slight change in the debugger

Before:
https://ibb.co/k9XFBMG

After:
https://ibb.co/N3cJ9V4

**Comment by caeser1996** [comment]
Can you try doing this in Nginx
```
server {
    listen 80;
    server_name team-mate.app;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name team-mate.app;

    ssl_certificate /path/to/cert.pem;
    ssl_certificate_key /path/to/cert.key;

    location / {
        proxy_pass http://uvicorn:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

```

**Comment by Lepiloff** [comment]
@caeser1996 Thanks for the advice. Tried it but the result is the same as in the post above.

**Comment by Lepiloff** [comment]
In the end, after many attempts to solve the problem, I managed to convert the application to work with https. Now the function `url_for` e.g. `href="{{ url_for('user_profile', pk=member.id) }}`" is correctly executed and redirects to the correct URL. Also, the warning in the browser that the connection is not secure is gone.

The trick was to use `--proxy-headers --forwarded-allow-ips` inside docker-compose

`command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload --proxy-headers --forwarded-allow-ips="*""`

and `X-Forwarded-Proto` in nginx config

`proxy_set_header    X-Forwarded-Proto   $scheme;`

There is one problem left to solve. I still get **404** for the static folder. Therefore, the styles don't work.

My current nginx-config

```
server {
    listen 80;
    server_name team-mate.app;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 443 ssl;
    server_name team-mate.app;
    server_tokens off;

    location /static/ {
        gzip            on;
        gzip_buffers    8 256k;
        alias /app/static/;
    }

    ssl_certificate /etc/letsencrypt/live/team-mate.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/team-mate.app/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header    Host                $host;
        proxy_set_header    X-Real-IP           $remote_addr;
        proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto   $scheme;
    }

    location /favicon.ico {
        access_log off;
        log_not_found off;
    }

}

```
and docker-compose.yaml

```
version: '3.9'

services:
  web:
    env_file: .env
    build: .
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload --proxy-headers --forwarded-allow-ips="*""
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  redis_data:
```
  
  
  Static file mount
  
```
  app = FastAPI()

app.mount("/static", StaticFiles(directory="static"), name="static")
```
