### DISCUSSION TITLE
Loading ML Models in Backgroud

### DISCUSSION THREAD

**Discussion by gaganmanku96** [fastapi/fastapi#6668] [Questions] [answered]
Hi, I've 3 deep learning models that I load when the application starts (by creating a global object) and it takes around 6-7 seconds to load completely. The problem is the endpoints do not start working until the models are loaded completely and in my Kubernetes, I cannot add a health check because it would give me connection failed.

Is there a way to load the models in the background and make the health check endpoint working?

Thank you

**Comment by raphaelauv** [comment, marked as answer]
NO you should not do it by a background process ! if your API is about exposing a ML model , than wait for it ! 

```yaml
...
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
```

put an initialDelaySeconds to your readinessProbe in the kubernetes yaml deployment
