### DISCUSSION TITLE
Flask to FastAPI conversion Kafka example for Kubernetes

### DISCUSSION THREAD

**Discussion by scheung38** [fastapi/fastapi#6752] [Questions] [answered]
1. How to convert from given Flask to FastAPI:
2. Will I get better performance doing so in this Kakfa context?

producer.py:

```
from flask import Flask, request, jsonify
from kafka import KafkaProducer
import json

app = Flask(__name__)
producer = KafkaProducer(bootstrap_servers='kafka:9092')
topic_name = 'messages'

@app.route('/', methods=["POST"])
def send():
    app.logger.info("received message")
    content = request.get_json()
    jd = json.dumps(content).encode('utf-8')
    producer.send(topic_name, jd)
    app.logger.info("sent message")
    return jsonify({"status":"ok"})

if __name__ == '__main__':
  app.logger.info('Starting server...')
  app.run(host='0.0.0.0', port=8080)
```
  
  
consumer.py: 

```
from kafka import KafkaConsumer

topic_name = 'messages'

if __name__ == '__main__':
  print('Starting consumer...')
  consumer = KafkaConsumer(topic_name, bootstrap_servers='kafka:9092')
  
  print('receiving messages...')
  for message in consumer:
      print(f'received message {message}')

  print('exiting...')
```

producer/okteto.yml:

```
name: producer
labels:
  stack.okteto.com/service: producer
command: bash
environment:
- FLASK_DEBUG=1
volumes:
- /root/.cache/pip
sync:
- .:/usr/src/app
forward:
- 8080:8080
reverse:
- 9000:9000
resources:
  limits:
    cpu: "1"
    memory: 2Gi
```

producer/Dockerfile:

```
FROM okteto/python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /usr/src/app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY app.py app.py
EXPOSE 8080
CMD ["python", "app.py" ]

```

consumer/okteto.yml:

```
name: consumer
labels:
  stack.okteto.com/service: consumer
command: bash
volumes:
- /root/.cache/pip
sync:
- .:/usr/src/app
reverse:
- 9000:9000
resources:
  limits:
    cpu: "1"
    memory: 2Gi
```

consumer/Dockerfile:
```
FROM okteto/python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /usr/src/app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY app.py app.py
EXPOSE 8080
CMD ["python", "app.py" ]
```

requirements.txt:

kafka-python
Flask==1.1.1
