### DISCUSSION TITLE
Docker Compose Template for Hello World Example

### DISCUSSION THREAD

**Discussion by yemregundogmus** [fastapi/fastapi#7019] [Questions] [answered]
Hi,

Can anyone share the basic docker-compose template for fastapi. 
I found the example below but couldn't figure out how to separate the postresql here and create the simple template.
Example: #1890

Have a nice Day!

**Comment by ycd** [comment]
I think a Dockerfile will be enough if you are going to use that example compose file without PostgreSQL 

As far as I understand [this](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker) should do good in your use case.

**Comment by includeamin** [comment, marked as answer]
as @ycd said a Dockerfile will be enough. but if you are going to have a docker-compose
[check this](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker#quick-start)
and then
``` yaml
version: '3'
services:
  fastapi:
    image: myimage
    ports:
    - "80:80"
```
or 
``` yaml
version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "880:80"
```
