### DISCUSSION TITLE
error, "[error] 33#33: *92500 connect() failed (111: Connection refused) while connecting to upstream, client: 216.58.212.244, server:

### DISCUSSION THREAD

**Discussion by JoshBello** [fastapi/fastapi#7241] [Questions] [answered]
Trying to host an API on App Engine using FastAPI, was originally using Flask which was working but very slow. I'm now getting the following error: `error, "[error] 33#33: *92500 connect() failed (111: Connection refused) while connecting to upstream, client: 216.58.212.244, server: `

This is the app.yaml file:

```
runtime: python
env: flex

entrypoint: uvicorn --host 127.0.0.1 --port 8080 --timeout-keep-alive 500 main:app
service: default

instance_class: F4_1G

# Instance Class: F4_1G
# Memory Limit: 2048 MB
# CPU Limit: 2.4 GHz
# Supported Scaling Types: Automatic

runtime_config:
    python_version: 3

handlers:
- url: /.*
  script: auto

network:
  forwarded_ports:
   - 8080
```

This is the main script, the majority of the code has had to be removed:

```
import uvicorn
from fastapi import FastAPI, Request
app = FastAPI()

@app.get('/')
async def nlp_email(return_method : str,
                    user_email    : str,
                    filename      : str)

    return {'html': html}
```
