### DISCUSSION TITLE
How to add descriptions to tags?

### DISCUSSION THREAD

**Discussion by timonbimon** [fastapi/fastapi#8098] [Questions] [answered]
**Description**

Is there a way to add a description to a tag?

**Additional context**
Before moving to FastAPI I always had descriptions for my tags in my openapi.yaml 

e.g.
```
tags:
- name: Feedback
  description: Endpoints to give feedback.
- name: Predictions
  description: Endpoints to get predictions.
```

Is there a way to easily achieve this with FastAPI?
