### DISCUSSION TITLE
FastAPI Authentication fail when using github actions for automated testing

### DISCUSSION THREAD

**Discussion by RamonJWS** [fastapi/fastapi#9427] [Questions] [answered]
### First Check

- [X] I added a very descriptive title here.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/pydantic/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
import pytest
import os

from fastapi.testclient import TestClient

from .test_utils import FakeUser
from settings import ROOT, PROJECT_DIR
from api import app
from db.database import SessionLocal
from db.models import DbBlog

automatic_fields = ['timestamp', 'id', 'image_url']
files_dir = os.path.join(ROOT, 'files')
client = TestClient(app)
user = FakeUser("a", "a")


def get_header():
    response = client.post("http://localhost:8000/token",
                           data={"grant_type": "password",
                                 "username": user.username,
                                 "password": user.password})

    if response.status_code == 200:
        access_token = response.json()["access_token"]
        return {"Authorization": f"Bearer {access_token}"}


@pytest.fixture
def delete_all_data():
    """
    This fixture runs on all tests apart from delete. This allows delete to be run on its own as well as with all tests.
    """

    # clean db
    session = SessionLocal()
    session.query(DbBlog).delete()
    session.commit()
    session.close()

    # clean dir with images
    if os.path.exists(files_dir):
        all_image_files = os.listdir(files_dir)
        for file in all_image_files:
            if file != '.gitkeep':
                os.remove(os.path.join(files_dir, file))


@pytest.fixture
def fake_data():
    response = client.post('/post', json={"user_name": "test name",
                                          "title": "test title",
                                          "content": "test content"},
                           headers=get_header())


def test_authentication(delete_all_data):
    """
    Authenticate fake user and check they can access a restricted endpoint
    """

    response = client.post("http://localhost:8000/token",
                             data={"grant_type": "password",
                                   "username": user.username,
                                   "password": user.password})

    assert response.status_code == 200


def test_authenticated_user_access(delete_all_data):
    response = client.get("http://localhost:8000/users/me", headers=get_header())
    assert response.status_code == 200
```

### Description

I'm trying to get my Github Action tests to pass but 6/7 of them fail due to 401 (Unauthorised). The only one that passes is my 'sign in' endpoint (`@router.post("/token")`). Interestingly all my tests pass locally which makes me think something is going wrong with my github secret key. The secret key is used to sign the JWT tokens.

I set my github secret key as follows:
1). Navigate to settings -> click secrets and variables -> click actions
2). Create a new repository secret -> enter name and enter secret value
3). Include secret in workflow yml:

```
name: Tests

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r backend/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test backend tests
      run: |
        # run backend tests
        pytest backend/tests/tests.py
```

My authentication process works pretty much the exact same way as on the FastAPIs website ([here][1])

My test code is as follows, I've only included 2 of test as the issue is the same for all tests. The first test "test_authentication" passes but "test_authenticated_user_access" fails:

```
import pytest
import os

from fastapi.testclient import TestClient

from .test_utils import FakeUser
from settings import ROOT, PROJECT_DIR
from api import app
from db.database import SessionLocal
from db.models import DbBlog

automatic_fields = ['timestamp', 'id', 'image_url']
files_dir = os.path.join(ROOT, 'files')
client = TestClient(app)
user = FakeUser("a", "a")


def get_header():
    response = client.post("http://localhost:8000/token",
                           data={"grant_type": "password",
                                 "username": user.username,
                                 "password": user.password})

    if response.status_code == 200:
        access_token = response.json()["access_token"]
        return {"Authorization": f"Bearer {access_token}"}


@pytest.fixture
def delete_all_data():
    """
    This fixture runs on all tests apart from delete. This allows delete to be run on its own as well as with all tests.
    """

    # clean db
    session = SessionLocal()
    session.query(DbBlog).delete()
    session.commit()
    session.close()

    # clean dir with images
    if os.path.exists(files_dir):
        all_image_files = os.listdir(files_dir)
        for file in all_image_files:
            if file != '.gitkeep':
                os.remove(os.path.join(files_dir, file))


@pytest.fixture
def fake_data():
    response = client.post('/post', json={"user_name": "test name",
                                          "title": "test title",
                                          "content": "test content"},
                           headers=get_header())


def test_authentication(delete_all_data):
    """
    Authenticate fake user and check they can access a restricted endpoint
    """

    response = client.post("http://localhost:8000/token",
                             data={"grant_type": "password",
                                   "username": user.username,
                                   "password": user.password})

    assert response.status_code == 200


def test_authenticated_user_access(delete_all_data):
    response = client.get("http://localhost:8000/users/me", headers=get_header())
    assert response.status_code == 200

...
```

Its worth noting that the tests passed both locally and during push before I added in authentication.

Would really appreciate a solution to this, i'm close to removing the test automation entirely... Thanks!

  [1]: https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/

### Operating System

macOS

### Operating System Details

local is MacOS, github actions machine is Ubuntu-latest

### FastAPI Version

fastapi==0.95.1

### Python Version

3.11
