### DISCUSSION TITLE
Expose FastAPI server routes on mulltiple ports

### DISCUSSION THREAD

**Discussion by junoriosity** [fastapi/fastapi#9491] [Questions]
### First Check

- [X] I added a very descriptive title here.
- [X] I used the GitHub search to find a similar question and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/pydantic/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
app = FastAPI()
app2 = FastAPI()

app2.mount("/metrics", metrics_app)
```

### Description

I want to scrape some metrics from my FastAPI server. However, I do not want to show it to the public in contrast to the remaining API.

Hence, I resolved to create a second server and tried to run (inspired by this [here](https://stackoverflow.com/questions/69641363/how-to-run-fastapi-app-on-multiple-ports))

```
version: '3.8'

services:

  scraiber_gpt:
    build:
      context: ./src
      dockerfile: Dockerfile.test
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000 & uvicorn app.main:app2 --reload --workers 1 --host 0.0.0.0 --port 8001
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8004:8000
      - 8005:8001
```

However, I cannot see anything from app2. 

Is there some way to make it work? 🙂

### Operating System

Linux

### FastAPI Version

0.95.1

### Python Version

3.11

**Comment by abhint** [comment]
```yaml
version: '3.8'

services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile.test
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8004:8000

  app2:
    build:
      context: ./src
      dockerfile: Dockerfile.test
    command: uvicorn app.main:app2 --reload --workers 1 --host 0.0.0.0 --port 8001
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8005:8001

```

**Reply by junoriosity** [reply]
@abhint Many thanks for your reply.

I also thought about such a solution, however, the metrics from all the resources of `app` that should be exposed by `app2` would not be exposable with such an approach or am I mistaken?

**Reply by junoriosity** [reply]
@abhint I mean if the `app` and `app2` were totally unrelated, I would just build separate servers.

However, `app` produces some metrics I am collecting. I do not want to expose these via `app` to the public. Instead I want to keep the `metrics` route private and route it via `app2` to another port.

This is the whole idea. However, if you have a better solution at hand, I would be happy to learn about it. 🙂

**Reply by abhint** [reply]
I have not used this method yet
[prometheus/client_python](https://github.com/prometheus/client_python)

**Reply by junoriosity** [reply]
@abhint This is what I use. However, I need to expose it separately.

**Comment by demaj** [comment]
Add a `wait` at the end of the entry command:
`command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000 & uvicorn app.main:app2 --reload --workers 1 --host 0.0.0.0 --port 8001 & wait`

**Reply by junoriosity** [reply]
@demaj Many thanks for your input. Sadly, I still cannot fetch the second endpoint data.

This is my `docker-compose` file

```
version: '3.8'

services:

 server:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000 & uvicorn app.main:app2 --reload --workers 1 --host 0.0.0.0 --port 8001 & wait
    volumes:
      - ./src:/src
    ports:
      - 8004:8000
      - 8005:8801
```
Do you have any other ideas I might try?
